// THIS FILE IS AUTOGENERATED //
// DO NOT EDIT THIS MANUALLY //

#pragma once

float pre_fade_LUT_get( float phase );
float rec_fade_LUT_get( float phase );
float equal_power_LUT_get( float phase );
